create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text,timezone text not null default 'Asia/Kolkata',gate_exam_date date not null default '2027-02-07',upsc_exam_date date not null default '2027-05-30',day_start time not null default '04:30',created_at timestamptz not null default now());
create table if not exists public.tasks(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null,task_date date not null default current_date,scheduled_time time,tag text not null default 'Study',priority text not null default 'Medium' check(priority in('Low','Medium','High')),done boolean not null default false,completed_at timestamptz,source text not null default 'manual',goal_id uuid,notes text,focus_seconds integer not null default 0,created_at timestamptz not null default now());
create table if not exists public.monthly_goals(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,month_start date not null,title text not null,category text,target_units integer not null default 0,completed_units integer not null default 0,deadline date,next_action text,progress numeric(5,2) not null default 0,color text not null default 'lime',created_at timestamptz not null default now());
create table if not exists public.study_sessions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,started_at timestamptz not null,ended_at timestamptz,minutes integer not null check(minutes>=0),subject text,focus_score integer check(focus_score between 1 and 10),created_at timestamptz not null default now());
create table if not exists public.quotes(id uuid primary key default gen_random_uuid(),quote text not null,author text,active boolean not null default true);
create table if not exists public.ai_command_log(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,command text not null,intent jsonb,result jsonb,created_at timestamptz not null default now());
alter table public.profiles add column if not exists day_start time not null default '04:30';
alter table public.tasks add column if not exists focus_seconds integer not null default 0;
alter table public.profiles enable row level security;alter table public.tasks enable row level security;alter table public.monthly_goals enable row level security;alter table public.study_sessions enable row level security;alter table public.quotes enable row level security;alter table public.ai_command_log enable row level security;
create policy "own profile" on public.profiles for all using(auth.uid()=id) with check(auth.uid()=id);create policy "own tasks" on public.tasks for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "own goals" on public.monthly_goals for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "own sessions" on public.study_sessions for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "public quotes" on public.quotes for select using(active=true);create policy "own ai logs" on public.ai_command_log for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
insert into public.quotes(quote,author) select * from(values
('Stand up. Open the book. The next 25 minutes are not optional.',null),
('Your exam date is fixed. Your excuses are not. Start the block now.',null),
('Nobody is coming to rescue this syllabus. Sit down and finish the next page.',null),
('You already know what to do. Stop shopping for a feeling and start the timer.',null),
('GATE and UPSC do not care that you are tired. Open the notes.',null),
('If you wait until you feel ready, you will lose the year. Begin in the next 10 seconds.',null)
) as s(quote,author) where not exists(select 1 from public.quotes where quote=s.quote);
