import React, { Component, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  Check, Clock, Plus, Sparkles, Target, LayoutDashboard, MessageCircle,
  Play, Pause, AlarmClock, X, Send, Loader2, Trash2,
} from 'lucide-react';
import './styles.css';
import { supabase } from './lib/supabase';
import { timeToMinutes } from './lib/study-engine';
import { fetchKickQuote, pickKickQuote } from './lib/quotes';
import {
  DEFAULT_DAY_START,
  formatRange,
  inferDayStartChange,
  planDayIntelligently,
  shiftClock,
  shiftTasks,
} from './lib/day-planner';

const pad = n => String(n).padStart(2, '0');
const today = () => { const d = new Date(); return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`; };
const monthStart = () => today().slice(0,7) + '-01';
const daysUntil = d => Math.max(0, Math.ceil((new Date(d)-new Date())/86400000));
const normTime = t => (t ? String(t).slice(0,5) : null);
const focusStorageKey = () => `studybot-focus-${today()}`;
const clearedDayKey = () => `studybot-cleared-${today()}`;
const accountStorageKey = suffix => `studybot-${suffix}`;
const isDayCleared = () => { try { return localStorage.getItem(clearedDayKey()) === '1'; } catch { return false; } };
const markDayCleared = cleared => { try { if(cleared)localStorage.setItem(clearedDayKey(),'1'); else localStorage.removeItem(clearedDayKey()); } catch {} };

const ROUTINE_SEED = [
  ['UPSC','06:00','08:30','UPSC','High','📚','upsc'],
  ['Supplements','08:45','09:00','Routine','Medium','💊','routine'],
  ['GATE','09:00','11:30','GATE','High','⚙️','gate'],
  ['UPSC','12:00','14:00','UPSC','High','📚','upsc'],
  ['DSA','14:30','16:30','DSA','High','💻','dsa'],
  ['DSA','18:00','20:00','DSA','High','💻','dsa'],
  ['Current Affairs','21:00','22:00','Current Affairs','High','🗞️','study'],
  ['RE-Vision','22:30','00:30','Revision','High','📝','study'],
];
function routineObjects(){return ROUTINE_SEED.map(([title,start,end,tag,priority,icon,tone])=>({title,start,end,tag,priority,icon,tone,duration:durationBetween(start,end)}));}
function durationBetween(start,end){const a=timeToMinutes(normTime(start)),b=timeToMinutes(normTime(end));if(a==null||b==null)return 25;return Math.max(1,b>a?b-a:b===a?1440:(b-a)+1440);}
function shiftedRoutine(dayStart=DEFAULT_DAY_START){const delta=(timeToMinutes(dayStart)??360)-(timeToMinutes(DEFAULT_DAY_START)??360);return routineObjects().map(r=>{const start=shiftClock(r.start,delta),end=shiftClock(r.end,delta);return {...r,start,end,time:formatRange(start,r.duration)};});}
function parseRoutineClock(raw){const s=String(raw||'').trim().toLowerCase().replace(/\./g,'');const m=s.match(/^(\d{1,2})(?::(\d{2}))?\s*(am|pm)?$/);if(!m)return null;let h=Number(m[1]),min=Number(m[2]||0),ap=m[3];if(ap==='pm'&&h<12)h+=12;if(ap==='am'&&h===12)h=0;if(h>23||min>59)return null;return `${pad(h)}:${pad(min)}`;}
function parseRoutineText(text){const rows=[];for(const raw of String(text||'').split(/\n+/)){const line=raw.trim();if(!line)continue;const m=line.match(/^\s*(\d{1,2}(?::\d{2})?\s*(?:a\.?m\.?|p\.?m\.?)?)\s*[-–]\s*(\d{1,2}(?::\d{2})?\s*(?:a\.?m\.?|p\.?m\.?)?)\s+(.+)$/i);if(!m)continue;const start=parseRoutineClock(m[1]),end=parseRoutineClock(m[2]);if(!start||!end)continue;const title=m[3].trim();const upper=title.toLowerCase();let tag='Personal',tone='college',icon='🧩';if(/upsc/.test(upper)){tag='UPSC';tone='upsc';icon='📚';}else if(/gate/.test(upper)){tag='GATE';tone='gate';icon='⚙️';}else if(/dsa/.test(upper)){tag='DSA';tone='dsa';icon='💻';}else if(/current|affairs/.test(upper)){tag='Current Affairs';tone='study';icon='🗞️';}else if(/revision|re-vision/.test(upper)){tag='Revision';tone='study';icon='📝';}else if(/supplement/.test(upper)){tag='Routine';tone='routine';icon='💊';}else if(/fresh|sleep|break|family|walk/.test(upper)){tag='Routine';tone='routine';icon='✨';}rows.push({title,start,end,duration:durationBetween(start,end),tag,priority:'High',icon,tone});}return rows.sort((a,b)=>a.start.localeCompare(b.start));}
function routineToText(rows){return (rows||[]).map(r=>`${r.start}-${r.end} ${plainTitle(r.title)}`).join('\n');}

const TASK_TAGS=['Personal','UPSC','GATE','DSA','Current Affairs','Revision','Routine'];
const PRIORITIES=['Low','Medium','High'];
const TAG_TONE={UPSC:'upsc',GATE:'gate',DSA:'dsa','Current Affairs':'study',Revision:'study',Routine:'routine',Personal:'college'};
const TAG_EMOJI={UPSC:'📚',GATE:'⚙️',DSA:'💻','Current Affairs':'🗞️',Revision:'📝',Routine:'✨',Personal:'🧩'};
const emojiFor=tag=>TAG_EMOJI[tag]||'🎯';
const plainTitle=title=>String(title||'').replace(/^[\u{1F000}-\u{1FAFF}\u2600-\u27BF]\uFE0F?\s*/u,'');
const QUICK_PROMPTS=['Plan my day','Start my day at 6:00 AM instead of 4:00 AM','What should I do next?','Move DSA to 8 PM'];
function formatFocus(seconds){const s=Math.max(0,Number(seconds)||0);if(s<60)return `${s}s`;const m=Math.floor(s/60);if(m<60)return `${m}m`;return `${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}m`;}
function formatClockHMS(seconds){const s=Math.max(0,Math.floor(Number(seconds)||0));return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function durationFromRange(time,fallback=25){const parts=String(time||'').split(/[–-]/).map(v=>normTime(v.trim())).filter(Boolean);if(parts.length>=2)return durationBetween(parts[0],parts[1]);return Math.max(1,Number(fallback)||25);}
function readFocusLog(){try{return JSON.parse(localStorage.getItem(focusStorageKey())||'{}');}catch{return {};}}
function writeFocusLog(log){try{localStorage.setItem(focusStorageKey(),JSON.stringify(log));}catch{}}
function FocusClock({progress,active,running,onClick,label}){const pct=Math.min(1,Math.max(0,Number(progress)||0)),angle=pct*360;return <button type="button" className={`focus-clock ${active?'active':''}`} onClick={onClick} aria-label={label} title={label}><span className="focus-clock-face" style={{background:`conic-gradient(from -90deg, #9ec5ff 0deg ${angle}deg, #0a2463 ${angle}deg 360deg)`}}/><span className="focus-clock-icon">{running?<Pause size={13} fill="currentColor"/>:<Play size={13} fill="currentColor"/>}</span></button>;}
function HeatMap({title,days,history,onSelect,showWeekdays=false}){const byDay=new Map();for(const task of history){const list=byDay.get(task.task_date)||[];list.push(task);byDay.set(task.task_date,list);}return <section className="heatmap" aria-label={title}><div className="heatmap-head"><strong>{title}</strong><span>🔴 none · 🟠 partial · 🟢 complete</span></div>{showWeekdays&&<div className="heatmap-weekdays">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(day=><span key={day}>{day}</span>)}</div>}<div className="heatmap-grid">{days.map(day=>{const list=byDay.get(day.key)||[],future=day.key>today(),state=future?'purple':!list.length?'red':list.every(t=>t.done)?'green':'orange';return <button type="button" className={`heat-cell ${state}`} key={day.key} onClick={()=>onSelect(day.key)} title={`${day.label}: ${future?'future day':!list.length?'no tasks':list.every(t=>t.done)?'all complete':'partially complete'}`}><span>{day.label}</span><b>{day.number}</b></button>;})}</div></section>;}
class AppErrorBoundary extends Component{state={error:null};static getDerivedStateFromError(error){return{error};}componentDidCatch(error,info){console.error('StudyBot crash',error,info);}render(){if(this.state.error)return <div className="shell"><main className="auth"><div className="auth-mark">!</div><h1>StudyBot<span>.</span></h1><p>Something went wrong while loading the dashboard.</p><button className="primary-button" onClick={()=>location.reload()}>Reload StudyBot</button></main></div>;return this.props.children;}}
function Sheet({title,onClose,onSubmit,submitLabel='Save',children}){return <div className="modal-backdrop" onClick={onClose}><form className="modal sheet" onClick={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSubmit();}}><div className="between mb-10"><h3 style={{margin:0}}>{title}</h3><button type="button" className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="task-list">{children}</div><div className="row mt-12" style={{gap:10}}><button type="button" className="soft-button" style={{flex:1}} onClick={onClose}>Cancel</button><button type="submit" className="primary-button" style={{flex:1}}>{submitLabel}</button></div></form></div>;}

const SWIPE_TRIGGER=72,SWIPE_MAX=96,LONG_PRESS_MS=3000;
function TaskRow({item,done,disabled,onToggle,onDelete,onReorder,focusedSeconds,focusProgress,focusing,onFocusToggle}){
  const[dragX,setDragX]=useState(0),cardRef=useRef(null),dragXRef=useRef(0),dragging=useRef(false),onDeleteRef=useRef(onDelete),itemRef=useRef(item);
  onDeleteRef.current=onDelete;itemRef.current=item;
  useEffect(()=>{const el=cardRef.current;if(!el)return undefined;let startX=0,startY=0,locked=null,using=null,longPress=null,reordering=false;
    const point=e=>{const t=e.touches?.[0]||e.changedTouches?.[0]||e;return{x:t.clientX,y:t.clientY};};
    const down=e=>{if(e.type.startsWith('pointer')&&e.pointerType!=='mouse')return;if(e.target.closest('button'))return;const kind=e.type.startsWith('touch')?'touch':'pointer';if(using&&using!==kind)return;using=kind;const p=point(e);dragging.current=true;locked=null;startX=p.x;startY=p.y;longPress=setTimeout(()=>{reordering=true;el.classList.add('reordering');navigator.vibrate?.(18);},LONG_PRESS_MS);};
    const move=e=>{if(e.type.startsWith('pointer')&&e.pointerType!=='mouse')return;if(!dragging.current)return;const kind=e.type.startsWith('touch')?'touch':'pointer';if(using&&using!==kind)return;const p=point(e),dx=p.x-startX,dy=p.y-startY;if(reordering){if(Math.abs(dy)>=36){onReorder(itemRef.current,dy<0?-1:1);startY=p.y;}e.preventDefault();return;}if(Math.abs(dx)>10||Math.abs(dy)>10)clearTimeout(longPress);if(!locked){if(Math.abs(dx)<8&&Math.abs(dy)<8)return;locked=Math.abs(dx)>Math.abs(dy)?'x':'y';}if(locked!=='x')return;e.preventDefault();const next=Math.min(0,Math.max(dx,-SWIPE_MAX));dragXRef.current=next;setDragX(next);};
    const up=e=>{if(e?.type?.startsWith('pointer')&&e.pointerType!=='mouse')return;if(!dragging.current)return;const kind=e?.type?.startsWith('touch')?'touch':'pointer';if(using&&kind&&using!==kind)return;dragging.current=false;clearTimeout(longPress);el.classList.remove('reordering');reordering=false;using=null;if(locked==='x'&&dragXRef.current<=-SWIPE_TRIGGER)onDeleteRef.current(itemRef.current);dragXRef.current=0;setDragX(0);locked=null;};
    el.addEventListener('pointerdown',down);el.addEventListener('pointermove',move);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);el.addEventListener('touchstart',down,{passive:true});el.addEventListener('touchmove',move,{passive:false});el.addEventListener('touchend',up);el.addEventListener('touchcancel',up);
    return()=>{clearTimeout(longPress);el.removeEventListener('pointerdown',down);el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up);el.removeEventListener('pointercancel',up);el.removeEventListener('touchstart',down);el.removeEventListener('touchmove',move);el.removeEventListener('touchend',up);el.removeEventListener('touchcancel',up);};
  },[]);
  return <div className="task-swipe"><div className="task-swipe-action" style={{opacity:Math.min(1,-dragX/SWIPE_TRIGGER)}}><Trash2 size={18}/></div><div ref={cardRef} className={`task-card ${done?'done':''} ${focusing?'focusing':''} ${item.rolled?'rolled':''}`} style={{transform:dragX?`translateX(${dragX}px)`:undefined,transition:dragging.current?'none':'transform .2s ease'}}><div className="task-icon">{item.icon}</div><div><div className="task-name">{plainTitle(item.title)} <span className="drag-handle" aria-label="Hold for 3 seconds, then drag to move this mission">⠿</span></div><div className="task-time">{item.time}{item.durationMinutes?` · ${item.durationMinutes}m`:''}</div><div className="pill-row"><span className={`pill cat-${item.tone}`}>{item.tag}</span>{item.rolled&&<span className="pill rollover-pill">↪ Rolled from yesterday</span>}{focusedSeconds>0&&<span className="focus-time">{formatFocus(focusedSeconds)} focused</span>}<button type="button" className="icon-button" style={{width:24,height:24,minHeight:0}} onClick={()=>onDelete(item)} aria-label={`Delete ${item.title}`}><Trash2 size={12}/></button></div></div><div className="check-wrap"><FocusClock progress={focusProgress} active={focusing} running={focusing} label={focusing?`Pause focus on ${item.title}`:`Start ${item.durationMinutes||25}m focus on ${item.title}`} onClick={e=>{e.stopPropagation();onFocusToggle(item);}}/><button type="button" disabled={disabled} aria-pressed={done} aria-label={done?`Mark ${item.title} as not done`:`Mark ${item.title} as done`} className={`checkbox-button ${done?'checked':''}`} onPointerDown={e=>e.stopPropagation()} onPointerUp={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();onToggle(item);}}>{done?<Check size={18}/>:<span/>}</button></div></div></div>;
}
function AuthScreen({mode,setMode,identifier,setIdentifier,passcode,setPasscode,confirm,setConfirm,submit,busy,error}){return <div className="shell"><main className="auth"><div className="auth-mark"><Target size={22}/></div><h1>StudyBot<span>.</span></h1><p className="muted">Your private study command center.</p><div className="auth-card"><div className="auth-tabs"><button type="button" className={mode==='signin'?'active':''} onClick={()=>{setMode('signin');setConfirm('');}}>Sign in</button><button type="button" className={mode==='signup'?'active':''} onClick={()=>setMode('signup')}>Create account</button></div><form onSubmit={e=>{e.preventDefault();submit();}}><label className="field full"><span>Email or phone</span><input autoFocus value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="you@example.com or +91..." autoComplete="username"/></label><label className="field full"><span>Passcode</span><input type="password" value={passcode} onChange={e=>setPasscode(e.target.value)} placeholder="At least 4 characters" autoComplete={mode==='signup'?'new-password':'current-password'}/></label>{mode==='signup'&&<label className="field full"><span>Confirm passcode</span><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repeat your passcode" autoComplete="new-password"/>}</label>}{error&&<div className="auth-error">{error}</div>}<button className="primary-button auth-submit" type="submit" disabled={busy}>{busy?<><Loader2 size={17} className="spin"/> Working…</>:mode==='signup'?'Create my account':'Sign in'}</button></form><p className="auth-note">Each account has its own goals, missions, routine, focus history, and settings. Data syncs across devices.</p></div></main></div>;}

function App(){
  const[user,setUser]=useState(null),[authReady,setAuthReady]=useState(false),[tasks,setTasks]=useState([]),[goals,setGoals]=useState([]),[weekHistory,setWeekHistory]=useState([]),[monthHistory,setMonthHistory]=useState([]),[selectedDay,setSelectedDay]=useState(null),[selectedDayTasks,setSelectedDayTasks]=useState([]),[historyLoading,setHistoryLoading]=useState(false),[tab,setTab]=useState('today'),[quote,setQuote]=useState(()=>pickKickQuote()),[toast,setToast]=useState(''),[saving,setSaving]=useState(''),[focusMinutes,setFocusMinutes]=useState(25),[timer,setTimer]=useState(25*60),[running,setRunning]=useState(false),[hours,setHours]=useState(6),[dayStart,setDayStart]=useState(DEFAULT_DAY_START),[focusLog,setFocusLog]=useState(()=>readFocusLog()),[activeFocusId,setActiveFocusId]=useState(null),[showAddTask,setShowAddTask]=useState(false),[showAddGoal,setShowAddGoal]=useState(false),[taskForm,setTaskForm]=useState({title:'',priority:'Medium',tag:'Personal',start:'',end:'',goalId:'',units:1}),[goalForm,setGoalForm]=useState({title:'',target:1,category:'DSA'}),[chatMessages,setChatMessages]=useState([]),[chatInput,setChatInput]=useState(''),[chatLoading,setChatLoading]=useState(false),[hydrated,setHydrated]=useState(false),[authMode,setAuthMode]=useState('signin'),[authIdentifier,setAuthIdentifier]=useState(''),[authPasscode,setAuthPasscode]=useState(''),[authConfirm,setAuthConfirm]=useState(''),[authBusy,setAuthBusy]=useState(false),[authError,setAuthError]=useState(''),[routine,setRoutine]=useState(()=>routineObjects()),[routineText,setRoutineText]=useState(()=>routineToText(routineObjects()));
  const chatEndRef=useRef(null),quoteRef=useRef(quote),activeFocusRef=useRef(null),sessionStampRef=useRef(null),timerTickRef=useRef(Date.now()),tasksRef=useRef([]),seededRef=useRef(false);quoteRef.current=quote;activeFocusRef.current=activeFocusId;tasksRef.current=tasks;
  const flash=m=>{setToast(String(m||'Something went wrong'));setTimeout(()=>setToast(''),3500);};
  const persistDayStart=value=>{setDayStart(value);try{localStorage.setItem(accountStorageKey(`day-start-${user?.id||'guest'}`),value);}catch{}};
  const refreshQuote=async()=>setQuote(await fetchKickQuote(quoteRef.current,supabase));
  useEffect(()=>{refreshQuote();const id=setInterval(()=>{if(document.visibilityState==='visible')refreshQuote();},75000);return()=>clearInterval(id);},[]);
  useEffect(()=>{let cancelled=false;const bootstrap=async()=>{const{data}=await supabase.auth.getSession();if(!cancelled){setUser(data?.session?.user||null);setAuthReady(true);}};bootstrap();const listener=supabase.auth.onAuthStateChange((_event,session)=>{if(!cancelled){setUser(session?.user||null);if(!session){setHydrated(false);setTasks([]);setGoals([]);}}});return()=>{cancelled=true;listener?.data?.subscription?.unsubscribe?.();};},[]);

  const load=async()=>{if(!user)return;try{const savedStart=localStorage.getItem(accountStorageKey(`day-start-${user.id}`));if(savedStart)setDayStart(savedStart);const rollover=await supabase.from('tasks').update({task_date:today(),notes:'rolled-over'}).eq('user_id',user.id).lt('task_date',today()).eq('done',false);if(rollover.error)throw rollover.error;const now=new Date(),monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));const weekFrom=`${monday.getFullYear()}-${pad(monday.getMonth()+1)}-${pad(monday.getDate())}`,monthFrom=`${now.getFullYear()}-${pad(now.getMonth()+1)}-01`,previous=new Date(now.getFullYear(),now.getMonth()-1,1),previousMonth=`${previous.getFullYear()}-${pad(previous.getMonth()+1)}-01`;
    const[a,b,priorGoals]=await Promise.all([supabase.from('tasks').select('*').eq('task_date',today()).order('scheduled_time'),supabase.from('monthly_goals').select('*').eq('month_start',monthStart()),supabase.from('monthly_goals').select('*').eq('month_start',previousMonth)]);if(a.error)throw a.error;if(b.error)throw b.error;if(priorGoals.error)throw priorGoals.error;const currentGoals=b.data||[];const carryRows=(priorGoals.data||[]).filter(g=>Number(g.completed_units||0)<Number(g.target_units||1)).filter(g=>!currentGoals.some(x=>x.title===g.title)).map(g=>({user_id:user.id,month_start:monthStart(),title:g.title,category:g.category,target_units:g.target_units,completed_units:0,deadline:g.deadline,next_action:g.next_action,progress:0,color:'purple'}));let carried=[];if(carryRows.length){const r=await supabase.from('monthly_goals').insert(carryRows).select();if(r.error)throw r.error;carried=r.data||[];}
    setTasks(a.data||[]);setGoals([...currentGoals,...carried]);const history=await supabase.from('tasks').select('task_date,done').gte('task_date',monthFrom).order('task_date');if(!history.error){setWeekHistory((history.data||[]).filter(t=>t.task_date>=weekFrom));setMonthHistory(history.data||[]);}const profile=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(!profile.error&&profile.data){if(profile.data.day_start)persistDayStart(normTime(profile.data.day_start));const savedRoutine=Array.isArray(profile.data.routine_json)&&profile.data.routine_json.length?profile.data.routine_json:routineObjects();setRoutine(savedRoutine);setRoutineText(routineToText(savedRoutine));}
    const nextLog={...readFocusLog()};for(const task of a.data||[]){const stored=Number(task.focus_seconds||0);if(stored>(nextLog[task.id]||0))nextLog[task.id]=stored;}setFocusLog(nextLog);writeFocusLog(nextLog);setHydrated(true);
  }catch(error){setHydrated(true);flash(error.message);}};
  useEffect(()=>{if(authReady&&user){seededRef.current=false;setChatMessages([{id:'seed',role:'bot',text:"Hey — I'm your StudyBot AI. I remember your routine, missions, monthly goals and focus history for this account."}]);load();}},[authReady,user]);
  useEffect(()=>{let current=today();const id=setInterval(()=>{const now=today();if(now!==current){current=now;load();setFocusLog(readFocusLog());}},60000);return()=>clearInterval(id);},[user]);
  useEffect(()=>{if(!running)return;sessionStampRef.current=sessionStampRef.current||new Date().toISOString();timerTickRef.current=Date.now();const tick=()=>{const elapsed=Math.max(0,Math.floor((Date.now()-timerTickRef.current)/1000));if(!elapsed)return;timerTickRef.current+=elapsed*1000;setTimer(v=>{if(v<=elapsed){setRunning(false);return 0;}return v-elapsed;});const key=activeFocusRef.current;if(!key)return;setFocusLog(prev=>{const next={...prev,[key]:(prev[key]||0)+elapsed};writeFocusLog(next);return next;});};const id=setInterval(tick,1000);document.addEventListener('visibilitychange',tick);window.addEventListener('focus',tick);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',tick);window.removeEventListener('focus',tick);};},[running]);
  useEffect(()=>chatEndRef.current?.scrollIntoView({behavior:'smooth',block:'end'}),[chatMessages,chatLoading,tab]);
  const persistFocusSeconds=async(taskId,seconds)=>{if(!user||!taskId)return;const{error}=await supabase.from('tasks').update({focus_seconds:seconds}).eq('id',taskId);if(error)flash(error.message);};
  const saveStudySession=async(taskItem,minutes)=>{if(!user||minutes<1)return;await supabase.from('study_sessions').insert({started_at:sessionStampRef.current||new Date().toISOString(),ended_at:new Date().toISOString(),minutes,subject:taskItem?.tag||taskItem?.title||'Focus'});};
  const resolveItemTask=async item=>{if(item.task?.id)return item.task;const{data,error}=await supabase.from('tasks').insert({title:plainTitle(item.title),task_date:today(),scheduled_time:item.start||null,end_time:item.end||null,duration_minutes:item.durationMinutes||durationBetween(item.start,item.end),priority:item.priority||'Medium',tag:item.tag||'Personal',source:item.source||'routine',done:false,goal_id:item.goalId||null,units:Number(item.units||1)}).select().single();if(error){flash(error.message);return null;}setTasks(v=>[...v,data]);return data;};
  const rememberTask=task=>{const next=tasksRef.current.some(t=>t.id===task.id)?tasksRef.current.map(t=>t.id===task.id?task:t):[...tasksRef.current,task];tasksRef.current=next;setTasks(next);};
  const refreshGoals=async()=>{const{data,error}=await supabase.from('monthly_goals').select('*').eq('month_start',monthStart());if(!error)setGoals(data||[]);};
  const toggleFocusFor=async item=>{const key=item.task?.id||item.focusKey;if(!key)return;if(activeFocusId===key&&running){setRunning(false);await persistFocusSeconds(key,focusLog[key]||0);const blockMin=Math.min(360,Math.max(1,Number(item.durationMinutes)||durationFromRange(item.time,25)));await saveStudySession(item,Math.max(1,Math.round(((blockMin*60)-timer)/60)));return;}const blockMin=Math.min(360,Math.max(1,Number(item.durationMinutes)||durationFromRange(item.time,25)));setFocusMinutes(blockMin);setTimer(Math.max(1,(blockMin*60)-(focusLog[key]||0)));setActiveFocusId(key);sessionStampRef.current=new Date().toISOString();setRunning(true);flash(`${plainTitle(item.title)}: ${blockMin}m focus block`);};
  const toggleItem=async item=>{if(saving||!user)return;setSaving('task');let task=item.task;const previousDone=task?.done??false;try{if(!task)task=await resolveItemTask(item);if(!task)throw new Error('This mission is not in your tracker yet.');const next=!previousDone;rememberTask({...task,done:next});const{data,error}=await supabase.from('tasks').update({done:next,completed_at:next?new Date().toISOString():null}).eq('id',task.id).select('id,done,completed_at,goal_id').single();if(error)throw error;rememberTask({...task,...data});await refreshGoals();flash(next?'Task completed ✓':'Task reopened');}catch(error){if(task)rememberTask({...task,done:previousDone});flash('Could not save task: '+error.message);}finally{setSaving('');}};
  const toggleGoal=async goal=>{if(!user||saving)return;setSaving(goal.id);const target=Math.max(1,Number(goal.target_units||1)),wasDone=Number(goal.completed_units||0)>=target,nextUnits=wasDone?0:target;setGoals(v=>v.map(g=>g.id===goal.id?{...g,completed_units:nextUnits}:g));try{const{error}=await supabase.from('monthly_goals').update({completed_units:nextUnits}).eq('id',goal.id);if(error)throw error;flash(wasDone?'Goal reopened':'Goal completed ✓');}catch(error){setGoals(v=>v.map(g=>g.id===goal.id?goal:g));flash('Could not save goal: '+error.message);}finally{setSaving('');}};
  const submitGoal=async()=>{const title=goalForm.title.trim();if(!title||!user)return;const{error}=await supabase.from('monthly_goals').insert({month_start:monthStart(),title,target_units:Math.max(1,Number(goalForm.target)||1),category:goalForm.category||null,completed_units:0,color:'blue'});if(error)flash(error.message);else{await refreshGoals();flash('Goal added');}setShowAddGoal(false);setGoalForm({title:'',target:1,category:'DSA'});};
  const submitTask=async()=>{const title=taskForm.title.trim();if(!title||!user)return;const duration=taskForm.start&&taskForm.end?durationBetween(taskForm.start,taskForm.end):25;const{error}=await supabase.from('tasks').insert({title,task_date:today(),scheduled_time:taskForm.start||null,end_time:taskForm.end||null,duration_minutes:duration,priority:taskForm.priority,tag:taskForm.tag||'Personal',source:'manual',done:false,goal_id:taskForm.goalId||null,units:Number(taskForm.units)||1});if(error)flash(error.message);else{markDayCleared(false);flash('Task added');await load();}setShowAddTask(false);setTaskForm({title:'',priority:'Medium',tag:'Personal',start:'',end:'',goalId:'',units:1});};
  const deleteTask=async id=>{if(!user||!id)return;const{error}=await supabase.from('tasks').delete().eq('id',id);if(error)flash(error.message);else{const next=tasksRef.current.filter(t=>t.id!==id);tasksRef.current=next;setTasks(next);if(!next.length)markDayCleared(true);await refreshGoals();flash(next.length?'Task removed':'All missions cleared for today.');}};
  const removeItem=async item=>{const task=item.task?.id?item.task:await resolveItemTask(item);if(task?.id)await deleteTask(task.id);else flash('This mission is not saved yet.');};
  const reorderTask=async(item,direction)=>{const current=item.task;if(!current?.id)return;const ordered=[...tasksRef.current].sort((a,b)=>(a.scheduled_time||'99:99').localeCompare(b.scheduled_time||'99:99'));const index=ordered.findIndex(t=>t.id===current.id),neighbour=ordered[index+direction];if(!neighbour)return;const currentTime=current.scheduled_time,nextTime=neighbour.scheduled_time,currentEnd=current.end_time,nextEnd=neighbour.end_time,swapped=ordered.map(t=>t.id===current.id?{...t,scheduled_time:nextTime,end_time:nextEnd}:t.id===neighbour.id?{...t,scheduled_time:currentTime,end_time:currentEnd}:t);tasksRef.current=swapped;setTasks(swapped);const[a,b]=await Promise.all([supabase.from('tasks').update({scheduled_time:nextTime,end_time:nextEnd}).eq('id',current.id),supabase.from('tasks').update({scheduled_time:currentTime,end_time:currentEnd}).eq('id',neighbour.id)]);if(a.error||b.error){flash('Could not move the mission.');load();}};
  const inspectDay=async day=>{setSelectedDay(day);setHistoryLoading(true);if(!user){setSelectedDayTasks([]);setHistoryLoading(false);return;}const{data,error}=await supabase.from('tasks').select('*').eq('task_date',day).order('scheduled_time');setSelectedDayTasks(error?[]:(data||[]));setHistoryLoading(false);};
  const loadRoutine=async(quiet=false,rows=routine)=>{const list=(rows&&rows.length?rows:routineObjects()).map(r=>({...r,title:plainTitle(r.title),duration:r.duration||durationBetween(r.start,r.end)}));if(!user||!list.length)return;try{await supabase.from('tasks').delete().eq('task_date',today()).eq('source','routine');const payload=list.map(r=>({title:r.title,task_date:today(),scheduled_time:r.start,end_time:r.end,duration_minutes:r.duration||durationBetween(r.start,r.end),priority:r.priority||'High',tag:r.tag||'Routine',source:'routine',done:false,units:1}));const{error}=await supabase.from('tasks').insert(payload).select();if(error)throw error;markDayCleared(false);if(!quiet)flash(`Routine loaded: ${list.length} blocks.`);await load();}catch(error){flash('Could not load routine: '+error.message);}};
  const saveRoutine=async()=>{const parsed=parseRoutineText(routineText);if(!parsed.length){flash('Use one interval per line, e.g. 06:00-06:30 Fresh up');return;}setRoutine(parsed);setRoutineText(routineToText(parsed));const first=parsed[0]?.start||dayStart;persistDayStart(first);const{error}=await supabase.from('profiles').update({day_start:first,routine_json:parsed,timezone:'Asia/Kolkata'}).eq('id',user.id);if(error){flash(error.message);return;}await loadRoutine(false,parsed);};
  useEffect(()=>{if(!hydrated||!user||seededRef.current)return;seededRef.current=true;if(!tasksRef.current.length&&!isDayCleared())loadRoutine(true);},[hydrated,user]);
  const saveProfileStart=async time=>{if(user)await supabase.from('profiles').update({day_start:time,timezone:'Asia/Kolkata'}).eq('id',user.id);};
  const replanDay=async currentTasks=>{const source=currentTasks||tasks,{tasks:next,plan}=planDayIntelligently(source,hours,today());setTasks(next);for(const task of next)await supabase.from('tasks').update({scheduled_time:task.scheduled_time,task_date:task.task_date||today()}).eq('id',task.id);flash(plan.overloaded?`Day packed. ${plan.deferred} lower-value block(s) could not fit into ${hours}h.`:`Day packed into ${hours} focused hours.`);return next;};
  const applyOperations=async ops=>{let local=[...tasks],planned=false;for(const op of ops){try{if(op.op==='create'){const start=op.time||null,end=op.end||null,duration=Number(op.duration_minutes)||((start&&end)?durationBetween(start,end):25);const{data,error}=await supabase.from('tasks').insert({title:plainTitle(op.title),task_date:op.task_date||today(),scheduled_time:start,end_time:end,duration_minutes:duration,priority:op.priority||'Medium',tag:op.tag||'Personal',source:'ai',done:false,goal_id:op.goal_id||null,units:Number(op.units||1)}).select().single();if(error)throw error;local=[...local,data];}
      else if(op.op==='update'){const patch={};if(op.new_title)patch.title=plainTitle(op.new_title);if(op.priority)patch.priority=op.priority;if(op.tag)patch.tag=op.tag;if(op.time!==undefined)patch.scheduled_time=op.time||null;if(op.end!==undefined)patch.end_time=op.end||null;if(op.time&&op.end)patch.duration_minutes=durationBetween(op.time,op.end);if(op.goal_id!==undefined)patch.goal_id=op.goal_id;if(op.units!==undefined)patch.units=Number(op.units)||1;if(Object.keys(patch).length){const{error}=await supabase.from('tasks').update(patch).eq('id',op.task_id);if(error)throw error;local=local.map(t=>t.id===op.task_id?{...t,...patch}:t);}}
      else if(op.op==='reschedule'){const patch={task_date:op.task_date||today(),scheduled_time:op.time||null,end_time:op.end||null};if(op.time&&op.end)patch.duration_minutes=durationBetween(op.time,op.end);const{error}=await supabase.from('tasks').update(patch).eq('id',op.task_id);if(error)throw error;local=local.map(t=>t.id===op.task_id?{...t,...patch}:t);}
      else if(op.op==='delete'){const{error}=await supabase.from('tasks').delete().eq('id',op.task_id);if(error)throw error;local=local.filter(t=>t.id!==op.task_id);}
      else if(op.op==='complete'){const{error}=await supabase.from('tasks').update({done:true,completed_at:new Date().toISOString()}).eq('id',op.task_id);if(error)throw error;local=local.map(t=>t.id===op.task_id?{...t,done:true}:t);}
      else if(op.op==='set_day_start'){const to=normTime(op.time);if(to){const delta=(timeToMinutes(to)??0)-(timeToMinutes(dayStart)??0);persistDayStart(to);saveProfileStart(to);local=shiftTasks(local,delta);for(const task of local)await supabase.from('tasks').update({scheduled_time:task.scheduled_time}).eq('id',task.id);const shifted=routine.map(r=>({...r,start:shiftClock(r.start,delta),end:shiftClock(r.end,delta)}));setRoutine(shifted);setRoutineText(routineToText(shifted));await supabase.from('profiles').update({day_start:to,routine_json:shifted}).eq('id',user.id);}}
      else if(op.op==='shift_day'){const delta=Number(op.delta_minutes)||0,nextStart=shiftClock(dayStart,delta);persistDayStart(nextStart);saveProfileStart(nextStart);local=shiftTasks(local,delta);for(const task of local)await supabase.from('tasks').update({scheduled_time:task.scheduled_time}).eq('id',task.id);}
      else if(op.op==='plan_day')planned=true;
    }catch(e){flash('AI action failed: '+e.message);}}
    setTasks(local);markDayCleared(!local.length);if(planned)await replanDay(local);else await load();await refreshGoals();};
  const sendCommand=async text=>{const command=(text??chatInput).trim();if(!command||chatLoading||!user)return;setChatMessages(v=>[...v,{id:crypto.randomUUID(),role:'user',text:command}]);setChatInput('');setChatLoading(true);try{const res=await fetch('/api/ai-task',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command,tasks,goals,today:today(),availableHours:hours,dayStart,routine})});const raw=await res.text();let data;try{data=JSON.parse(raw);}catch{throw new Error('AI endpoint is not reachable here.');}if(!res.ok)throw new Error(data.error||'AI request failed');const ops=Array.isArray(data.operations)?data.operations:[],needsConfirmation=!!data.needs_confirmation;setChatMessages(v=>[...v,{id:crypto.randomUUID(),role:'bot',text:data.message||'Done.',operations:ops,needsConfirmation,resolved:!needsConfirmation}]);if(!needsConfirmation)await applyOperations(ops);}catch(error){setChatMessages(v=>[...v,{id:crypto.randomUUID(),role:'bot',text:"Couldn't reach the AI — "+error.message}]);}finally{setChatLoading(false);}};
  const confirmMessage=async id=>{const msg=chatMessages.find(m=>m.id===id);if(!msg)return;await applyOperations(msg.operations||[]);setChatMessages(v=>v.map(m=>m.id===id?{...m,resolved:true}:m));flash('Applied.');};
  const dismissMessage=id=>setChatMessages(v=>v.map(m=>m.id===id?{...m,resolved:true,dismissed:true}:m));
  const doAuth=async()=>{setAuthError('');const id=authIdentifier.trim();if(!id||!authPasscode){setAuthError('Email/phone and passcode are required.');return;}if(authMode==='signup'&&authPasscode!==authConfirm){setAuthError('Passcodes do not match.');return;}setAuthBusy(true);try{const result=authMode==='signup'?await supabase.auth.signUpWithPasscode(id,authPasscode):await supabase.auth.signInWithPasscode(id,authPasscode);if(result.error)throw result.error;setUser(result.data.user);setAuthPasscode('');setAuthConfirm('');}catch(e){setAuthError(e.message);}finally{setAuthBusy(false);}};
  const signOut=async()=>{await supabase.auth.signOut();setUser(null);setTasks([]);setGoals([]);setHydrated(false);setTab('today');setAuthMode('signin');};

  const allItems=tasks.map(task=>{const duration=Number(task.duration_minutes)||durationBetween(task.scheduled_time,task.end_time)||25;return{key:task.id,task,title:plainTitle(task.title),tag:task.tag||'Personal',priority:task.priority,tone:TAG_TONE[task.tag]||'college',icon:emojiFor(task.tag),time:task.scheduled_time?formatRange(normTime(task.scheduled_time),duration):'Anytime',durationMinutes:duration,focusKey:task.id,start:task.scheduled_time,end:task.end_time};});
  const totalCount=allItems.length,completedCount=allItems.filter(i=>i.task?.done).length,completionPct=totalCount?Math.round((completedCount/totalCount)*100):0,focusedToday=Object.values(focusLog).reduce((a,b)=>a+Number(b||0),0),currentActiveItem=allItems.find(i=>i.focusKey===activeFocusId);
  const calendarDays=(count,start)=>Array.from({length:count},(_,index)=>{const d=new Date(start);d.setDate(d.getDate()+index);return{key:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,label:count===7?['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][index]:String(d.getDate()),number:d.getDate()};});
  const monday=new Date();monday.setHours(0,0,0,0);monday.setDate(monday.getDate()-((monday.getDay()+6)%7));const weeklyDays=calendarDays(7,monday);const firstOfMonth=new Date();firstOfMonth.setDate(1);firstOfMonth.setHours(0,0,0,0);const monthlyDays=calendarDays(new Date(firstOfMonth.getFullYear(),firstOfMonth.getMonth()+1,0).getDate(),firstOfMonth);
  const dayHistoryPanel=selectedDay&&<div className="day-history card"><div className="between"><strong>📜 {selectedDay} history</strong><button type="button" className="icon-button" onClick={()=>setSelectedDay(null)} aria-label="Close day history"><X size={16}/></button></div>{historyLoading?<div className="small muted mt-8">Loading tasks…</div>:selectedDayTasks.length?<div className="day-history-list mt-8">{selectedDayTasks.map(task=><div key={task.id} className={`day-history-task ${task.done?'done':''}`}><span>{emojiFor(task.tag)} {plainTitle(task.title)}</span><small>{normTime(task.scheduled_time)||'Anytime'}{task.end_time?` – ${normTime(task.end_time)}`:''} · {task.done?'done':'pending'}</small></div>)}</div>:<div className="empty-state mt-8">No tasks are available for this day.</div>}</div>;
  if(!authReady)return <div className="shell"><main className="auth loading-screen"><div className="auth-mark"><Loader2 className="spin" size={22}/></div><h1>StudyBot<span>.</span></h1><p className="muted">Preparing your private study space…</p></main></div>;
  if(!user)return <AuthScreen mode={authMode} setMode={m=>{setAuthMode(m);setAuthError('');}} identifier={authIdentifier} setIdentifier={setAuthIdentifier} passcode={authPasscode} setPasscode={setAuthPasscode} confirm={authConfirm} setConfirm={setAuthConfirm} submit={doAuth} busy={authBusy} error={authError}/>;
  return <div className="shell"><div className="top-panel"><div className="quote-banner"><Sparkles size={15} className="quote-icon"/><div className="quote">{quote}</div><button type="button" className="icon-button" onClick={refreshQuote} aria-label="Fetch a new kick-start line"><Sparkles size={16}/></button></div><div className="hero-row mt-8"><div className="greeting"><h1>{tab==='today'?'Good to see you.':tab==='chat'?'StudyBot AI':tab==='goals'?'Goals that matter':'Focus'}</h1><div className="date-line">{today()} · {user.identifier} · day starts {dayStart}</div></div><button type="button" className="soft-button account-button" onClick={signOut}>Sign out</button></div><div className="mini-stats"><div className="stat-chip"><span>TODAY</span><strong>{completionPct}%</strong></div><div className="stat-chip"><span>GATE 2027</span><strong>{daysUntil(user.gateExamDate||'2027-02-07')}d</strong></div><div className="stat-chip"><span>UPSC 2027</span><strong>{daysUntil(user.upscExamDate||'2027-05-30')}d</strong></div></div></div>
  <div className="content">
    {tab==='today'&&<><HeatMap title="📅 This week" days={weeklyDays} history={weekHistory} onSelect={inspectDay}/>{dayHistoryPanel}<div className="between"><div className="section-title" style={{margin:0}}>🎯 Mission list</div><button type="button" className="soft-button" onClick={()=>setShowAddTask(true)}><Plus size={16}/> Add</button></div>{allItems.length?<><p className="muted small mt-8" style={{marginBottom:10}}>{completedCount}/{totalCount} blocks complete. Play starts the exact focus block for that mission.</p><div className="progress"><span style={{width:completionPct+'%'}}/></div><div className="task-list mt-12">{allItems.map(item=>{const key=item.focusKey,focusing=running&&activeFocusId===key,blockSeconds=Math.max(60,(item.durationMinutes||focusMinutes)*60),consumed=focusing?Math.min(1,1-timer/blockSeconds):Math.min(1,(focusLog[key]||0)/blockSeconds);return <TaskRow key={item.key} item={item} done={!!item.task?.done} disabled={saving==='task'} onToggle={toggleItem} onDelete={removeItem} onReorder={reorderTask} focusedSeconds={focusLog[key]||0} focusProgress={consumed} focusing={focusing} onFocusToggle={toggleFocusFor}/>;})}</div><p className="small muted mt-8" style={{textAlign:'center'}}>Swipe left to delete · hold for 3 seconds, then drag up/down to reorder.</p></>:<div className="empty-state mt-12"><div className="task-name" style={{marginBottom:6}}>No missions for today.</div>You cleared the deck. Load your routine when you are ready.</div>}<button type="button" className="soft-button mt-12" style={{width:'100%',justifyContent:'center'}} onClick={()=>loadRoutine(false)}><AlarmClock size={16}/> Load routine into today's tracker</button></>}
    {tab==='goals'&&<><HeatMap title="🗓️ This month" days={monthlyDays} history={monthHistory} onSelect={inspectDay} showWeekdays/>{dayHistoryPanel}<div className="between"><div className="section-title" style={{margin:0}}>🌟 Month</div><button type="button" className="soft-button" onClick={()=>setShowAddGoal(true)}><Plus size={16}/> Add</button></div><div className="goals-list mt-12">{goals.length?goals.map(goal=>{const target=Math.max(1,Number(goal.target_units||1)),done=Number(goal.completed_units||0)>=target,pct=done?100:Math.round((Number(goal.completed_units||0)/target)*100);return <div className={`goal-card ${goal.color==='blue'?'gate':''} ${goal.color==='purple'?'rolled-goal':''}`} key={goal.id}><div className="row" style={{gap:10}}><button type="button" disabled={saving===goal.id} className={`checkbox-button ${done?'checked':''}`} aria-pressed={done} onClick={()=>toggleGoal(goal)}>{done?<Check size={18}/>:<span/>}</button><div style={{flex:1}}><div className="task-name" style={{textDecoration:done?'line-through':'none',color:done?'var(--text-secondary)':'inherit'}}>{plainTitle(goal.title)}</div><div className="mini-progress mt-8"><span style={{width:pct+'%'}}/></div><div className="small muted mt-8">{goal.completed_units||0}/{target} · {pct}%{goal.category?` · ${goal.category}`:''}{goal.color==='purple'?' · carried from last month':''}</div></div></div></div>;}) : <div className="empty-state">Add the outcomes you want this month.</div>}</div></>}
    {tab==='focus'&&<><div className="card today-focus-hero"><div className="countdown-label"><Clock size={16}/>Focused today</div><div className="today-focus-time">{formatClockHMS(focusedToday)}</div><div className="countdown-sub">{currentActiveItem?`${running?'Running':'Paused'} · ${plainTitle(currentActiveItem.title)} · ${Math.floor(timer/60)}:${String(timer%60).padStart(2,'0')} left`:'Tap play on a mission clock to start its exact block.'}</div></div><div className="task-list mt-16">{allItems.filter(item=>(focusLog[item.focusKey]||0)>0||(running&&activeFocusId===item.focusKey)).length?allItems.filter(item=>(focusLog[item.focusKey]||0)>0||(running&&activeFocusId===item.focusKey)).map(item=><div className="card" key={item.key} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><div><div className="task-name">{plainTitle(item.title)}</div><div className="task-time">{item.time}</div></div><strong className="mono" style={{color:'#1553a5'}}>{formatFocus(focusLog[item.focusKey]||0)}</strong></div>):<div className="empty-state">No focused minutes yet today. Start a mission clock on Today.</div>}</div></>}
    {tab==='chat'&&<><div className="card mb-10"><div className="section-title" style={{margin:'0 0 8px'}}>Routine</div><p className="muted small" style={{marginTop:0}}>Enter one interval per line. Use 30-minute granularity where possible. Example: <strong>06:00-06:30 Fresh up</strong>.</p><textarea className="chat-input" style={{width:'100%',minHeight:190,resize:'vertical',padding:12,lineHeight:1.5}} value={routineText} onChange={e=>setRoutineText(e.target.value)} placeholder={'06:00-06:30 Fresh up\n06:30-08:30 UPSC\n08:30-09:00 Breakfast'}/><button type="button" className="primary-button mt-12" style={{width:'100%',justifyContent:'center'}} onClick={saveRoutine}><AlarmClock size={16}/> Save routine & load today</button></div><div className="chat-window">{chatMessages.map(m=><div key={m.id} className={`message ${m.role}`}>{m.role==='bot'?<div className="bot-row"><div className="avatar"><MessageCircle size={16}/></div><div><div>{m.text}</div>{m.needsConfirmation&&!m.resolved&&<div className="row mt-8" style={{gap:8}}><button type="button" className="primary-button" style={{minHeight:36,padding:'6px 10px'}} onClick={()=>confirmMessage(m.id)}>Confirm</button><button type="button" className="soft-button" style={{minHeight:36,padding:'6px 10px'}} onClick={()=>dismissMessage(m.id)}>Cancel</button></div>}{m.dismissed&&<div className="small muted mt-8">Cancelled.</div>}</div></div>:m.text}</div>)}{chatLoading&&<div className="message bot"><div className="bot-row"><div className="avatar"><Loader2 size={16} className="spin"/></div><div className="loading-dots"><span/><span/><span/></div></div></div>}<div ref={chatEndRef}/></div><div className="quick-row mt-12">{QUICK_PROMPTS.map(q=><button key={q} type="button" className="quick-chip" disabled={chatLoading} onClick={()=>sendCommand(q)}>{q}</button>)}</div><div className="chat-compose"><input className="chat-input" placeholder="Ask StudyBot to plan, reschedule, complete, or time a mission…" value={chatInput} onChange={e=>setChatInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')sendCommand();}} disabled={chatLoading}/><button type="button" className="primary-button" style={{padding:0}} disabled={chatLoading||!chatInput.trim()} onClick={()=>sendCommand()}><Send size={18}/></button></div></>}
  </div>
  <nav className="tabbar"><button type="button" className={`tab-button ${tab==='today'?'active':''}`} onClick={()=>setTab('today')}><LayoutDashboard className="tab-icon" size={18}/><span>Today</span></button><button type="button" className={`tab-button ${tab==='chat'?'active':''}`} onClick={()=>setTab('chat')}><MessageCircle className="tab-icon" size={18}/><span>AI Chat</span></button><button type="button" className={`tab-button ${tab==='goals'?'active':''}`} onClick={()=>setTab('goals')}><Target className="tab-icon" size={18}/><span>Goals</span></button><button type="button" className={`tab-button ${tab==='focus'?'active':''}`} onClick={()=>setTab('focus')}><Clock className="tab-icon" size={18}/><span>Focus</span></button></nav>
  {toast&&<div className="toast-stack"><div className="toast">{toast}</div></div>}
  {showAddTask&&<Sheet title="Add task" onClose={()=>setShowAddTask(false)} onSubmit={submitTask}><div className="field full"><span>Title</span><input autoFocus type="text" value={taskForm.title} onChange={e=>setTaskForm(f=>({...f,title:e.target.value}))} placeholder="e.g. Revise Polity notes"/></div><div className="form-grid"><div className="field"><span>Start time</span><input type="time" value={taskForm.start} onChange={e=>setTaskForm(f=>({...f,start:e.target.value}))}/></div><div className="field"><span>End time</span><input type="time" value={taskForm.end} onChange={e=>setTaskForm(f=>({...f,end:e.target.value}))}/></div></div><div className="form-grid"><div className="field"><span>Priority</span><select value={taskForm.priority} onChange={e=>setTaskForm(f=>({...f,priority:e.target.value}))}>{PRIORITIES.map(p=><option key={p} value={p}>{p}</option>)}</select></div><div className="field"><span>Units</span><input type="number" min="1" value={taskForm.units} onChange={e=>setTaskForm(f=>({...f,units:e.target.value}))}/></div></div><div className="field full"><span>Tag / monthly-goal category</span><select value={taskForm.tag} onChange={e=>setTaskForm(f=>({...f,tag:e.target.value}))}>{TASK_TAGS.map(t=><option key={t} value={t}>{t}</option>)}</select></div><div className="field full"><span>Link to monthly goal (optional)</span><select value={taskForm.goalId} onChange={e=>setTaskForm(f=>({...f,goalId:e.target.value}))}><option value="">Auto-link by tag</option>{goals.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></div></Sheet>}
  {showAddGoal&&<Sheet title="Add monthly goal" onClose={()=>setShowAddGoal(false)} onSubmit={submitGoal}><div className="field full"><span>Goal</span><input autoFocus type="text" value={goalForm.title} onChange={e=>setGoalForm(f=>({...f,title:e.target.value}))} placeholder="e.g. DSA"/></div><div className="form-grid"><div className="field"><span>Category</span><select value={goalForm.category} onChange={e=>setGoalForm(f=>({...f,category:e.target.value}))}>{TASK_TAGS.map(t=><option key={t} value={t}>{t}</option>)}</select></div><div className="field"><span>Target units</span><input type="number" min="1" value={goalForm.target} onChange={e=>setGoalForm(f=>({...f,target:e.target.value}))}/></div></div></Sheet>}
  </div>;
}
createRoot(document.getElementById('root')).render(<AppErrorBoundary><App/></AppErrorBoundary>);
