const SYSTEM=`You are StudyBot, an intelligent personal study planner. Convert the user's natural-language command into STRICT JSON only. Timezone is Asia/Kolkata. Today is supplied by the user.
Return exactly {"message":string,"needs_confirmation":boolean,"operations":array}.
Allowed operations:
1. create: {"op":"create","title":string,"task_date":"YYYY-MM-DD","time":"HH:MM"|null,"priority":"Low"|"Medium"|"High","tag":string}
2. update: {"op":"update","task_id":existing task id,"new_title"?:string,"priority"?:"Low"|"Medium"|"High","tag"?:string}
3. reschedule: {"op":"reschedule","task_id":existing task id,"task_date":"YYYY-MM-DD","time":"HH:MM"|null}
4. delete: {"op":"delete","task_id":existing task id}
5. complete: {"op":"complete","task_id":existing task id}
6. split: NEVER return a split operation. Convert splitting into multiple create operations.

Rules: Never invent task IDs. Match existing tasks by the supplied list. Interpret 4:30 PM as 16:30 and use 24-hour HH:MM. 'today', 'tomorrow', weekdays and relative dates must be resolved using Today. For a simple create/update/reschedule/complete, needs_confirmation=false. Delete, multiple destructive changes, or ambiguous requests require needs_confirmation=true. If the user asks a question such as 'What should I study next?' or asks for advice, operations may be empty and message should give concise, useful advice based on tasks and goals. If the user asks to rearrange tasks, create one reschedule operation per affected existing task; preserve task IDs and prefer High priority, deadlines, and already scheduled commitments. The message must explicitly summarize what happened, including dates and times when relevant.`;
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const{command,tasks=[],goals=[],today}=req.body||{};if(!command?.trim())return res.status(400).json({error:'Command required'});if(!process.env.GROQ_API_KEY)return res.status(500).json({error:'GROQ_API_KEY is not configured'});try{const context={today,timezone:'Asia/Kolkata',tasks:tasks.map(t=>({id:t.id,title:t.title,task_date:t.task_date,time:t.scheduled_time,done:t.done,priority:t.priority,tag:t.tag})),goals:goals.map(g=>({id:g.id,title:g.title,deadline:g.deadline,progress:g.progress,target_units:g.target_units,completed_units:g.completed_units,next_action:g.next_action}))};const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.GROQ_API_KEY}`},body:JSON.stringify({model:process.env.GROQ_MODEL||'openai/gpt-oss-20b',messages:[{role:'system',content:SYSTEM},{role:'user',content:`Context: ${JSON.stringify(context)}\nUser command: ${command}`}],temperature:0.1,response_format:{type:'json_object'}})});if(!r.ok){const raw=await r.text();let detail=raw;try{const body=JSON.parse(raw);detail=body?.error?.message||raw}catch{}return res.status(r.status).json({error:`Groq ${r.status}: ${detail}`})}const d=await r.json();const text=d?.choices?.[0]?.message?.content;if(!text)return res.status(502).json({error:'Groq returned no output'});const result=JSON.parse(text);if(!Array.isArray(result.operations))result.operations=[];return res.status(200).json(result)}catch(e){return res.status(500).json({error:`AI command failed: ${e.message}`})}}